# Generated by Django 3.0.5 on 2020-04-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='selected_answer',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
