# Generated by Django 3.0.5 on 2020-04-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(
                blank=True, choices=[('REAL', 'REAL'), ('FAKE', 'FAKE')], max_length=10
            ),
        )
    ]
